Update CI_CD-Server.yml

diff --git a/.github/workflows/CI_CD-Server.yml b/.github/workflows/CI_CD-Server.yml
--- a/.github/workflows/CI_CD-Server.yml
+++ b/.github/workflows/CI_CD-Server.yml
@@ -19,44 +19,44 @@ env:
 
 
 jobs:
-  CI-ubuntu:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4.1.1
+  # CI-ubuntu:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - uses: actions/checkout@v4.1.1
 
-    - name: Cache 📂
-      id: cache-setup
-      #uses: action/cache@v4.0.1
-      run: ls
+  #   - name: Cache 📂
+  #     id: cache-setup
+  #     #uses: action/cache@v4.0.1
+  #     run: ls
       
 
-    - name: Setup .NET 📦
-      uses: actions/setup-dotnet@v4.0.0
-      with:
-        dotnet-version: ${{ env.DOTNET_VERSION }}
+  #   - name: Setup .NET 📦
+  #     uses: actions/setup-dotnet@v4.0.0
+  #     with:
+  #       dotnet-version: ${{ env.DOTNET_VERSION }}
         
-    - name: Install dependencies 📂
-      run: |
-        dotnet workload restore
+  #   - name: Install dependencies 📂
+  #     run: |
+  #       dotnet workload restore
 
-    - name: Build 🧱
-      run: dotnet build -c Release --no-restore
+  #   - name: Build 🧱
+  #     run: dotnet build -c Release --no-restore
       
-    - name: Test 🧪
-      run: dotnet test xU_Server -c Release --no-build --logger "trx;LogFileName=test-results-server-ubuntu.trx" || true
+  #   - name: Test 🧪
+  #     run: dotnet test xU_Server -c Release --no-build --logger "trx;LogFileName=test-results-server-ubuntu.trx" || true
 
-    - name: Publish Test Result 🚀
-      uses: dorny/test-reporter@v1
-      if: always()
-      with:
-        name: Report Tests Ubuntu
-        path: "**/test-results-server-ubuntu.trx"
-        reporter: dotnet-trx
-        fail-on-error: false
+  #   - name: Publish Test Result 🚀
+  #     uses: dorny/test-reporter@v1
+  #     if: always()
+  #     with:
+  #       name: Report Tests Ubuntu
+  #       path: "**/test-results-server-ubuntu.trx"
+  #       reporter: dotnet-trx
+  #       fail-on-error: false
         
   CI-windows:
     runs-on: windows-latest
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
+    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
     - uses: actions/checkout@v4.1.1
 
@@ -67,9 +67,10 @@ jobs:
         
     - name: Install dependencies 📂
       run: |
-        dotnet restore
         dotnet workload restore
-
+        dotnet restore
+        ls
+      
     - name: Build 🧱
       run: dotnet build -c Release --no-restore
       
@@ -85,36 +86,36 @@ jobs:
         reporter: dotnet-trx
         fail-on-error: false
 
-  CI-macos:
-    runs-on: macos-latest
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
-    steps:
-    - uses: actions/checkout@v4.1.1
+  # CI-macos:
+  #   runs-on: macos-latest
+  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
+  #   steps:
+  #   - uses: actions/checkout@v4.1.1
 
-    - name: Setup .NET 📦
-      uses: actions/setup-dotnet@v4.0.0
-      with:
-        dotnet-version: ${{ env.DOTNET_VERSION }}
+  #   - name: Setup .NET 📦
+  #     uses: actions/setup-dotnet@v4.0.0
+  #     with:
+  #       dotnet-version: ${{ env.DOTNET_VERSION }}
         
-    - name: Install dependencies 📂
-      run: |
-        dotnet restore
-        dotnet workload restore
+  #   - name: Install dependencies 📂
+  #     run: |
+  #       dotnet restore
+  #       dotnet workload restore
 
-    - name: Build 🧱
-      run: dotnet build -c Release --no-restore
+  #   - name: Build 🧱
+  #     run: dotnet build -c Release --no-restore
       
-    - name: Test 🧪
-      run: dotnet test xU_Server -c Release --no-build --logger "trx;LogFileName=test-results-server-macos.trx" || true
+  #   - name: Test 🧪
+  #     run: dotnet test xU_Server -c Release --no-build --logger "trx;LogFileName=test-results-server-macos.trx" || true
 
-    - name: Publish Test Result 🚀
-      uses: dorny/test-reporter@v1
-      if: always()
-      with:
-        name: Report Tests Macos
-        path: "**/test-results-server-macos.trx"
-        reporter: dotnet-trx
-        fail-on-error: false
+  #   - name: Publish Test Result 🚀
+  #     uses: dorny/test-reporter@v1
+  #     if: always()
+  #     with:
+  #       name: Report Tests Macos
+  #       path: "**/test-results-server-macos.trx"
+  #       reporter: dotnet-trx
+  #       fail-on-error: false
 
 
 
